--------------------------------------------------------
-- Archivo creado  - domingo-abril-19-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."CLIENTE" 
   (	"IDCLIENTE" NUMBER(10,0), 
	"NOMBRES" VARCHAR2(25 BYTE), 
	"APELLIDOS" VARCHAR2(35 BYTE), 
	"DNI" NUMBER, 
	"SEXO" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;


 
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."CLIENTE_PK" ON "PRUEBA"."CLIENTE" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PRUEBA"."CLIENTE" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
 
  ALTER TABLE "PRUEBA"."CLIENTE" MODIFY ("NOMBRES" NOT NULL ENABLE);
 
  ALTER TABLE "PRUEBA"."CLIENTE" MODIFY ("APELLIDOS" NOT NULL ENABLE);
 
  ALTER TABLE "PRUEBA"."CLIENTE" MODIFY ("DNI" NOT NULL ENABLE);
 
  ALTER TABLE "PRUEBA"."CLIENTE" MODIFY ("SEXO" NOT NULL ENABLE);


 

